### ISSUE TITLE
Panic "illegal base64 data at input byte 0" when doing GetChannelState

### ISSUE THREAD

**Issue by Chris-Ricketts** [singnet/snet-daemon#171]
I'm following the [How to Publish a SingularityNET Service (Example 2) Tutorial](https://github.com/singnet/wiki/tree/master/tutorials/howToPublishService).
After running `snet client get_channel_state CHANNEL_ID SERVICE_ENDPOINT` the snet-daemon panics with the following output:
```
DEBU[0283] GetChannelState called                        context="context.Background.WithCancel.WithCancel.WithValue(peer.peerKey{}, &peer.Peer{Addr:(*net.TCPAddr)(0xc4208f66c0), AuthInfo:credentials.AuthInfo(nil)}).WithValue(metadata.mdIncomingKey{}, metadata.MD{\":authority\":[]string{\"localhost:7000\"}, \"content-type\":[]string{\"application/grpc\"}, \"user-agent\":[]string{\"grpc-python/1.17.0 grpc-c/7.0.0 (manylinux; chttp2; gizmo)\"}, \"grpc-accept-encoding\":[]string{\"identity,deflate,gzip\"}, \"accept-encoding\":[]string{\"identity,gzip\"}}).WithValue(grpc.streamKey{}, <stream: 0xc4200e4400, /escrow.PaymentChannelStateService/GetChannelState>)" request="channel_id:\"u\" signature:\"\\3163U\\365m\\365a\\275\\014p\\352\\037\\004=!y\\303\\273\\034\\327\\031n\\354\\276\\265a4\\210\\377\\256\\267\\004FY\\223-t\\205@\\242\\315kY\\315\\273\\236~\\271^\\2736\\203\\331\\200\\226\\337a\\237\\3061L\\367\\375\\\"\\034\" "
DEBU[0283] Message signature parsed                      keyOwnerAddress="[206 53 232 229 230 64 70 46 223 245 226 119 226 225 192 20 147 194 177 137]" message="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHU=" messageHash=957055c12f6d4544bb3108120ae3bf01011cf5fdab8fa6fdf3cfaf1c3ffb12aa publicKey="&{0xc4200b4750 109474407193344080122002149430083545830858665848251655880203035698533787743175 38901542510788989968368284473304585020444400753866599922266247124794501267598}" signature="zjNV9W31Yb0McOofBD0hecO7HNcZbuy+tWE0iP+utwRGWZMtdIVAos1rWc27nn65Xrs2g9mAlt9hn8YxTPf9Ihw="
DEBU[0284] Channel found in blockchain                   channel="&{[206 53 232 229 230 64 70 46 223 245 226 119 226 225 192 20 147 194 177 137] [206 53 232 229 230 64 70 46 223 245 226 119 226 225 192 20 147 194 177 137] [6 226 137 231 5 147 172 90 118 135 194 201 154 205 121 81 115 87 71 209 58 198 220 173 137 238 110 74 23 43 100 243] 1 0 11000000}" channelID=117
PANI[0284] Error trying to base64.StdEncoding.DecodeString  error="illegal base64 data at input byte 0"
panic: (*logrus.Entry) (0x131e500,0xc4209bcaa0)

goroutine 244 [running]:
github.com/singnet/snet-daemon/vendor/github.com/sirupsen/logrus.Entry.log(0xc4200be3c0, 0xc4208946c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/vendor/github.com/sirupsen/logrus/entry.go:126 +0x2d2
github.com/singnet/snet-daemon/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc4209bca50, 0xc420505598, 0x1, 0x1)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/vendor/github.com/sirupsen/logrus/entry.go:194 +0xaa
github.com/singnet/snet-daemon/blockchain.GetDaemonGroupID(0x0, 0x0, 0x0, 0x0)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/blockchain/serviceMetadata.go:56 +0x2c2
github.com/singnet/snet-daemon/escrow.NewBlockchainChannelReader.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/escrow/payment_channel_storage.go:102 +0x2f
github.com/singnet/snet-daemon/escrow.(*BlockchainChannelReader).GetChannelStateFromBlockchain(0xc4204b82d0, 0xc4200bc080, 0x0, 0x413500, 0x0, 0x0)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/escrow/payment_channel_storage.go:118 +0xba
github.com/singnet/snet-daemon/escrow.(*lockingPaymentChannelService).PaymentChannel(0xc4201ec960, 0xc4200bc080, 0x20, 0xc42044a190, 0x41, 0x50)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/escrow/escrow.go:44 +0x7e
github.com/singnet/snet-daemon/escrow.(*PaymentChannelStateService).GetChannelState(0xc4204b8430, 0x15d1b40, 0xc42082c7e0, 0xc42082c810, 0xc4204b8430, 0xc4208f6ab0, 0x1173380)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/escrow/state_service.go:42 +0x350
github.com/singnet/snet-daemon/escrow._PaymentChannelStateService_GetChannelState_Handler(0x113fbc0, 0xc4204b8430, 0x15d1b40, 0xc42082c7e0, 0xc4200fd030, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/escrow/state_service.pb.go:159 +0x241
github.com/singnet/snet-daemon/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420b9e1c0, 0x15dbf40, 0xc4203de200, 0xc4200e4400, 0xc4201ecc60, 0x1f312f0, 0x0, 0x0, 0x0)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/vendor/google.golang.org/grpc/server.go:1011 +0x4fc
github.com/singnet/snet-daemon/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420b9e1c0, 0x15dbf40, 0xc4203de200, 0xc4200e4400, 0x0)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/vendor/google.golang.org/grpc/server.go:1249 +0x1318
github.com/singnet/snet-daemon/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42098f710, 0xc420b9e1c0, 0x15dbf40, 0xc4203de200, 0xc4200e4400)
	/home/anand/singnet/src/github.com/singnet/snet-daemon/vendor/google.golang.org/grpc/server.go:680 +0x9f
created by github.com/singnet/snet-daemon/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/anand/singnet/src/github.com/singnet/snet-daemon/vendor/google.golang.org/grpc/server.go:678 +0xa1
```

**Comment by vsbogd** [comment]
Hi @Chris-Ricketts, thank you for reporting it. The most probably root cause is that service metadata was not actually read from IPFS.

Is it possible to copy full log of snet-daemon here? If it is too long you can replace ```log``` section of the ```snetd.config.json``` from tutorial by:
```json
   "LOG": {
       "LEVEL": "debug",
       "OUTPUT": {
            "TYPE": "file"
           }
   }
```
And send me ```snet-daemon.*.log``` files by email.

**Comment by Chris-Ricketts** [comment]
Hi @vsbogd, no problem. I've copied the full log file [to this pastebin](https://pastebin.com/uJCphcMB) as I wasn't sure of your email address.

**Comment by vsbogd** [comment]
@Chris-Ricketts, could you please check with snet-daemon version 1.3, I have published Dockerfile at https://github.com/singnet/wiki/blob/7ea3f26ccb98bb02c92d119b51d4c25c1a451db2/tutorials/Docker/Dockerfile

**Comment by Chris-Ricketts** [comment]
@vsbogd Sorry for the delay. I tested it and the error message is correct.

**Comment by vsbogd** [comment]
Sorry, I have found that I didn't mentioned this earlier, but to fix an issue you need to either update service endpoint to `http://localhost:7000` or set new value `https://localhost:7000` to `daemon_end_point` property in the `snetd.config.json`. Any of this should fix the issue.

My opinion it is not a bug in a daemon, it works as expected in this situation (at least version 1.3). So should the issue be closed?

**Comment by Chris-Ricketts** [comment]
Thanks for your patience @vsbogd - I managed to complete the tutorial after realising my mistake with the endpoints. I agree its not a bug and will close it.
