### ISSUE TITLE
cryptic error message with wrong SERVICE_ID in config

### ISSUE THREAD

**Issue by noskill** [singnet/snet-daemon#206]
if SERVICE_ID in snetd.config.json contains incorrect value snetd fails to start with hard to understand error message. I suggest changing error message to `can't find service metadata in ipfs with path <>`
```
PANI[0001] error executing the cat command in ipfs       error="cat: invalid 'ipfs ref' path" hashFromMetaData=
INFO[0001] [skipped leadership transfer for single member cluster]  pkg=etcdserver
panic: (*logrus.Entry) (0x130d2a0,0xc420c37770)

goroutine 1 [running]:
github.com/singnet/snet-daemon/vendor/github.com/sirupsen/logrus.Entry.log(0xc4200aa410, 0xc420944a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/singnet/src/github.com/singnet/snet-daemon/vendor/github.com/sirupsen/logrus/entry.go:126 +0x2d2
github.com/singnet/snet-daemon/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc420c37720, 0xc420487500, 0x1, 0x1)
        /root/singnet/src/github.com/singnet/snet-daemon/vendor/github.com/sirupsen/logrus/entry.go:194 +0xaa
github.com/singnet/snet-daemon/ipfsutils.GetIpfsFile(0x0, 0x0, 0x15a9e90, 0x0)
        /root/singnet/src/github.com/singnet/snet-daemon/ipfsutils/ipfsutils.go:19 +0x8e9
github.com/singnet/snet-daemon/blockchain.GetServiceMetaDataFromIPFS(0x0, 0x0, 0x0, 0x0, 0x0)
        /root/singnet/src/github.com/singnet/snet-daemon/blockchain/serviceMetadata.go:106 +0x35
github.com/singnet/snet-daemon/blockchain.ServiceMetaData(0xc4201743f0)
        /root/singnet/src/github.com/singnet/snet-daemon/blockchain/serviceMetadata.go:57 +0xa6
github.com/singnet/snet-daemon/snetd/cmd.(*Components).ServiceMetaData(0xc420423960, 0xc4201743f0)
        /root/singnet/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:101 +0x2f
github.com/singnet/snet-daemon/snetd/cmd.(*Components).Blockchain(0xc420423960, 0xf)
        /root/singnet/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:88 +0x81
github.com/singnet/snet-daemon/snetd/cmd.newDaemon(0xc420423960, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/singnet/src/github.com/singnet/snet-daemon/snetd/cmd/serve.go:123 +0x31b
github.com/singnet/snet-daemon/snetd/cmd.glob..func4(0x1f1d6c0, 0x1fa3d50, 0x0, 0x0)
        /root/singnet/src/github.com/singnet/snet-daemon/snetd/cmd/serve.go:56 +0x149
github.com/singnet/snet-daemon/snetd/cmd.glob..func3(0x1f1d6c0, 0x1fa3d50, 0x0, 0x0)
        /root/singnet/src/github.com/singnet/snet-daemon/snetd/cmd/flags.go:39 +0x9b
github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra.(*Command).execute(0x1f1d6c0, 0xc42009c190, 0x0, 0x0, 0x1f1d6c0, 0xc42009c190)
        /root/singnet/src/github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1f1d6c0, 0xc4202cbf78, 0x406aec, 0xc42008c058)
        /root/singnet/src/github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra.(*Command).Execute(0x1f1d6c0, 0x0, 0x0)
        /root/singnet/src/github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /root/singnet/src/github.com/singnet/snet-daemon/snetd/main.go:10 +0x31
```

**Comment by anandrgitnirman** [comment]
Fixed  with pull request #208

**Comment by noskill** [comment]
Thanks
