### ISSUE TITLE
Error Starting Daemon with Blockchain Disabled

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-daemon#365]
The below was seen 

panic: runtime error: invalid memory address or nil pointer dereference
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x778f92]

goroutine 1 [running]:
github.com/singnet/snet-daemon/vendor/github.com/ethereum/go-ethereum/ethclient.(*Client).Close(0x0)
    /ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:59 +0x22
github.com/singnet/snet-daemon/blockchain.(*Processor).Close(0xc420194690)
    /ext-go/1/src/github.com/singnet/snet-daemon/blockchain/blockchain.go:119 +0x2f
github.com/singnet/snet-daemon/snetd/cmd.(*Components).Close(0xc42020bf40)
    /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:87 +0x50
panic(0x1170060, 0x1f218d0)
    /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/singnet/snet-daemon/snetd/cmd.(*Components).GrpcInterceptor(0xc42020bf40, 0xc4206be2d0)
    /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:236 +0x5b
github.com/singnet/snet-daemon/snetd/cmd.(*daemon).start(0xc4208800c0)
    /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/serve.go:180 +0x24d
github.com/singnet/snet-daemon/snetd/cmd.glob..func3(0x1f30320, 0xc4203f0dc0, 0x0, 0x2)
    /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/serve.go:63 +0x1ca
github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra.(*Command).execute(0x1f30320, 0xc4203f0d60, 0x2, 0x2, 0x1f30320, 0xc4203f0d60)
    /ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1f30580, 0xc4204d1f78, 0x406bfc, 0xc4200a8058)
    /ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra.(*Command).Execute(0x1f30580, 0x0, 0x0)
    /ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()

**Comment by anandrgitnirman** [comment]
ETCD shoudl not be used when Block chain is disabled, is there a reason to use etcd when block chain is disabled ? 
@vsbogd
