### ISSUE TITLE
SIGSEGV kills daemon on metrics publishing

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#417]
I am trying to call `example-service` in docker and getting `SIGSEGV` on metering message signing. After `panic` daemon dies:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ae3e8]

goroutine 142 [running]:
github.com/singnet/snet-daemon/vendor/github.com/ethereum/go-ethereum/crypto.Sign(0xc4202c26e0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/ethereum/go-ethereum/crypto/signature_cgo.go:58 +0x68
github.com/singnet/snet-daemon/authutils.GetSignature(0xc420342150, 0x26, 0x26, 0x0, 0x0, 0x0, 0xc420342150)
	/ext-go/1/src/github.com/singnet/snet-daemon/authutils/auth_service.go:118 +0x148
github.com/singnet/snet-daemon/metrics.signForMeteringValidation(0x0, 0xc4205c21a0, 0x132fa92, 0x6, 0xc420805ee0, 0x7, 0xc4203b93f8, 0x7)
	/ext-go/1/src/github.com/singnet/snet-daemon/metrics/utils.go:148 +0x37c
github.com/singnet/snet-daemon/metrics.SignMessageForMetering(0xc42010ab00, 0xc420805ee0)
	/ext-go/1/src/github.com/singnet/snet-daemon/metrics/utils.go:114 +0x13b
github.com/singnet/snet-daemon/metrics.sendRequest(0xc420488000, 0x24a, 0x2d1, 0xc4204ea320, 0x41, 0xc420805ee0, 0x15a6370, 0xc4205a4000, 0x24a)
	/ext-go/1/src/github.com/singnet/snet-daemon/metrics/utils.go:95 +0x29a
github.com/singnet/snet-daemon/metrics.publishJson(0xc420488000, 0x24a, 0x2d1, 0xc4204ea320, 0x41, 0x1, 0xc420805ee0, 0xc4204ea35b)
	/ext-go/1/src/github.com/singnet/snet-daemon/metrics/utils.go:69 +0x64
github.com/singnet/snet-daemon/metrics.Publish(0x112ff60, 0xc42010a700, 0xc4204ea320, 0x41, 0xc420805ee0, 0xc4204ea320)
	/ext-go/1/src/github.com/singnet/snet-daemon/metrics/utils.go:60 +0xb8
github.com/singnet/snet-daemon/metrics.PublishRequestStats(0xc4202f2270, 0x15c3a20, 0xc4200f2c60, 0xc4202f2270)
	/ext-go/1/src/github.com/singnet/snet-daemon/metrics/request_stats.go:36 +0x3c8
created by github.com/singnet/snet-daemon/handler.interceptMonitoring
	/ext-go/1/src/github.com/singnet/snet-daemon/handler/interceptors.go:177 +0x12b
2019-11-07 09:57:49,313 - [   ERROR] - run_example_service - [Errno 3] No such process
```

Daemon configuration:
```
# cat snetd_configs/snetd.local.json 
{
  "daemon_end_point": "0.0.0.0:7000",
  "ipfs_end_point": "http://localhost:5002",
  "blockchain_network_selected": "local",
  "passthrough_enabled": true,
  "passthrough_endpoint": "http://localhost:7003",
  "organization_id": "snet",
  "service_id": "example-service",

  "log": {
    "level": "debug",
    "output": {
      "current_link": "./snetd-local.log",
      "file_pattern": "./snetd-local.%Y%m%d.log",
      "rotation_count": 0,
      "rotation_time_in_sec": 86400,
      "type": "file"
    }
  }
}
```

Daemon version:
```
# snetd version
INFO[0000] Cobra initialized                            
INFO[0000] Configuration file is not set, using default configuration 
version tag: v2.0.2
built on: 2019-08-22_05:49:53
sha1 revision: 2c3c3e8aad1cda9bcefa33e3f9261476fb09e721
```

**Comment by anandrgitnirman** [comment]
Checking this

**Comment by anandrgitnirman** [comment]
hi @vsbogd , we had intentially put in a check to make sure that all configuratios related to metering are set up ( as part of free call support on Beta 2) , however this should not be forced .. 
We dicused this internally too a few days back and feel Free calls will be supported by Daemon ONLY when you have certain metering configs set up , 
so how about this ,
1) Have a flag to support free calls from your Daemon , turn this off by default
2) If you want support of free calls, then ensure ( give better description on what is mandatory) 
    we are also looking at the free call support being a part of service metata data ( For future) ,

**Comment by anandrgitnirman** [comment]
@vsbogd , can you post your organization metadata published too ?

**Comment by vsbogd** [comment]
Organization metadata:
```
# snet organization print-metadata snet snet
{
    "org_name": "snet",
    "org_id": "snet",
    "groups": [
        {
            "group_name": "default_group",
            "group_id": "aft+fPjiApTaknPrcjTuV/UZvmjGSRJ5eCNHi5/tKp4=",
            "payment": {
                "payment_address": "0x592E3C0f3B038A0D673F19a18a773F993d4b2610",
                "payment_expiration_threshold": 100,
                "payment_channel_storage_type": "etcd",
                "payment_channel_storage_client": {
                    "connection_timeout": "100s",
                    "request_timeout": "5s",
                    "endpoints": [
                        "http://localhost:2379"
                    ]
                }
            }
        }
    ]
}
```

**Comment by vsbogd** [comment]
It is my own local environment, `snet` is just name I used locally.

**Comment by vsbogd** [comment]
Main issue in current implementation is that it has monitoring enabled by default but there is no default private key, so if you didn't set private key for monitoring then daemon crashes.

I think your suggestion to have flag to enable free calls makes sense. By default configuration will not require private key. If service provider would like to enable FreeCalls he should setup monitoring properly.

**Comment by anandrgitnirman** [comment]
> It is my own local environment, `snet` is just name I used locally.

to start ETCD locally, just add this config as well on your daemon ( unless you have started ETCD already seprately  )
"payment_channel_storage_server": {
	"enabled": true
	}

**Comment by vsbogd** [comment]
Yes, I use separate ETCD instance.
