### ISSUE TITLE
segmentation fault after update to version 4.0

### ISSUE THREAD

**Issue by noskill** [singnet/snet-daemon#511]
after update of snetd it produces segfault soon after start:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0xbecd17]

goroutine 1 [running]:
github.com/singnet/snet-daemon/vendor/github.com/coreos/etcd/clientv3.(*Client).Ctx(...)
        /ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/coreos/etcd/clientv3/client.go:110
github.com/singnet/snet-daemon/vendor/github.com/coreos/etcd/clientv3/concurrency.NewSession(0x0, 0x0, 0x0, 0x0, 0x174876e800, 0x0, 0x0)
        /ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/coreos/etcd/clientv3/concurrency/session.go:39 +0x37
github.com/singnet/snet-daemon/etcddb.NewEtcdClientFromVip(0xc4201ac0f0, 0xc420114f80, 0x863ab7, 0x10ebe60, 0xc42003b730)
        /ext-go/1/src/github.com/singnet/snet-daemon/etcddb/etcddb_client.go:85 +0x2af
github.com/singnet/snet-daemon/etcddb.NewEtcdClient(0xc420114f80, 0xc420114f80, 0x8701a1, 0xc4201ac0f0)
        /ext-go/1/src/github.com/singnet/snet-daemon/etcddb/etcddb_client.go:47 +0x37
github.com/singnet/snet-daemon/snetd/cmd.(*Components).EtcdClient(0xc4203428c0, 0x1c)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:171 +0x53
github.com/singnet/snet-daemon/snetd/cmd.(*Components).AtomicStorage(0xc4203428c0, 0xc420613590, 0x0)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:208 +0x360
github.com/singnet/snet-daemon/snetd/cmd.(*Components).MPESpecificStorage(0xc4203428c0, 0xc4200ccc80)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:226 +0x45
github.com/singnet/snet-daemon/snetd/cmd.(*Components).PaymentChannelService(0xc4203428c0, 0xc4200e6230, 0xc4204e64b0)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:265 +0x4f
github.com/singnet/snet-daemon/snetd/cmd.(*Components).EscrowPaymentHandler(0xc4203428c0, 0x1, 0x1)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:300 +0x49
github.com/singnet/snet-daemon/snetd/cmd.(*Components).GrpcPaymentValidationInterceptor(0xc4203428c0, 0xc42040eb10)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:456 +0x256
github.com/singnet/snet-daemon/snetd/cmd.(*Components).GrpcInterceptor(0xc4203428c0, 0xc420517980)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/components.go:375 +0x10f
github.com/singnet/snet-daemon/snetd/cmd.(*daemon).start(0xc4204b4180)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/serve.go:179 +0x24d
github.com/singnet/snet-daemon/snetd/cmd.glob..func3(0x1f43bc0, 0x1fcafc8, 0x0, 0x0)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/serve.go:63 +0x1ca
github.com/singnet/snet-daemon/snetd/cmd.glob..func2(0x1f43bc0, 0x1fcafc8, 0x0, 0x0)
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/cmd/flags.go:39 +0x9b
github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra.(*Command).execute(0x1f43bc0, 0xc4200a6190, 0x0, 0x0, 0x1f43bc0, 0xc4200a6190)
        /ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1f43bc0, 0xc4202ddf78, 0x406bfc, 0xc420096058)
        /ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra.(*Command).Execute(0x1f43bc0, 0x0, 0x0)
        /ext-go/1/src/github.com/singnet/snet-daemon/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /ext-go/1/src/github.com/singnet/snet-daemon/snetd/main.go:10 +0x31
```

snetd version

```                                    
version tag: v4.0.0
built on: 2020-08-10_11:11:07
sha1 revision: ee0dbc26136b367ea5a16c26da12ea95d59e9f00
```

**Comment by anandrgitnirman** [comment]
please make sure you have the latest etcd certficates, however we will add better error handling than a nil pointer dereference
